//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchPagingSorting.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_table
    {
        public int customer_id { get; set; }
        public string Cust_fname { get; set; }
        public string csut_sname { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
